#!/bin/bash

BRANCH=$(git symbolic-ref --short HEAD)
REGEX="^(feat|bug|fix)\/[0-9]+\/[[:alnum:]-]+$"

if [[ ! $BRANCH =~ $REGEX ]]; then
  echo "========================"
  echo ""
  echo -e "> \e[31mYour commit was rejected due to the branch name\e[0m"
  echo ""
  echo -e "> Please rename your branch using the syntax: \e[32m(feat|bug|fix)\/\e[34mnotion-task-id-numbers\/\e[33mbranch-objective\e[0m"
  echo "> Commits in the develop, main, or qa branches are not allowed."
  echo ""
  echo "========================"
  exit 1
fi

MESSAGE=$(cat $1) 
COMMITFORMAT="^(feat|fix|docs|style|ref|test|setup)(\((.*)\))?:\s?(.*)$"

if ! [[ "$MESSAGE" =~ $COMMITFORMAT ]]; then
  echo "========================"
  echo " "
  echo -e "\e[31mYour commit was rejected due to the commit message. COMMIT FAILED !\e[0m" 
  echo ""
  echo "Please use the following format..."
  echo ""
  echo "feat: feature example comment"
  echo "fix: fix example comment"
  echo "bug: bugfix example comment"
  echo "docs: docs example comment"
  echo "style: style example comment"
  echo "ref: ref example comment"
  echo "test: test example comment"
  echo " "
  echo "========================"
  exit 1
fi