import GetCampaignByIdOperation from 'src/core/campaigns/operations/campaigns/GetCampaignByIdOperation';
import createCampaignOperation from 'src/core/campaigns/operations/campaigns/CreateCampaignOperation';
import GetAllCampaignsOperation from 'src/core/campaigns/operations/campaigns/GetAllCampaignsOperation';
import UpdateMatchMapImagesOperation from 'src/core/campaigns/operations/campaigns/UpdateMatchMapImagesOperation';
import UpdateMatchImagesOperation from 'src/core/campaigns/operations/UpdateMatchImagesOperation';
import UpdateMatchHighlightedImageOperation from 'src/core/campaigns/operations/UpdateMatchHighlightedImageOperation';
import UpdateMatchMusicsOperation from 'src/core/campaigns/operations/campaigns/UpdateMatchMusicsOperation';
import UpdateCampaignOperation from 'src/core/campaigns/operations/campaigns/UpdateCampaignOperation';
import PublishmentOperation from 'src/core/campaigns/operations/campaigns/PublishmentOperation';
import AddCampaignPlayersOperation from 'src/core/campaigns/operations/campaigns/AddCampaignPlayersOperation';
import RemoveCampaignPlayersOperation from 'src/core/campaigns/operations/campaigns/RemoveCampaignPlayersOperation';
import PostCampaignBuyOperation from 'src/core/campaigns/operations/PostCampaignBuyOperation';
import AddPlayerCharacterOperation from 'src/core/campaigns/operations/AddPlayerCharacterOperation';
import RemovePlayerCharacterOperation from 'src/core/campaigns/operations/RemovePlayerCharacterOperation';
import GetCampaignCharactersOperation from 'src/core/campaigns/operations/GetCampaignCharactersOperation';
import GetCharactersByPlayerOperation from 'src/core/campaigns/operations/GetCharactersByPlayerOperation';
import GetCampaignsByUserIdOperation from 'src/core/users/operations/users/GetCampaignsByUserIdOperation';
import ConfirmMatchPlayerPresenceOperation from 'src/core/campaigns/operations/ConfirmMatchPlayerPresenceOperation';
import ConfirmCampaignPlayerOperation from 'src/core/campaigns/operations/ConfirmCampaignPlayerOperation';
import UpdateCampaignCoverOperation from 'src/core/campaigns/operations/UpdateCampaignCoverOperation';
import RemoveCampaignImageOperation from 'src/core/campaigns/operations/RemoveCampaignImageOperation';
import TransferDungeonMasterOperation from 'src/core/campaigns/operations/TransferDungeonMasterOperation';
import UpdateCampaignJournalHighlightOperation from 'src/core/campaigns/operations/UpdateCampaignJournalHighlightOperation';
import UpdateCampaignJournalPostOperation from 'src/core/campaigns/operations/UpdateCampaignJournalPostOperation';
import DeleteCampaignJournalPostOperation from 'src/core/campaigns/operations/DeleteCampaignJournalPostOperation';
import DeleteCampaignOperation from 'src/core/campaigns/operations/DeleteCampaignOperation';
import UpdateCampaignPlayerNoteOperation from 'src/core/campaigns/operations/UpdateCampaignPlayerNoteOperation';
import RemoveCampaignPlayerNoteOperation from 'src/core/campaigns/operations/RemoveCampaignPlayerNoteOperation';

export interface CampaignsControllerContract {
    [key: string]: unknown;
    deleteCampaignOperation: DeleteCampaignOperation;
    getAllCampaignsOperation: GetAllCampaignsOperation;
    getCampaignByIdOperation: GetCampaignByIdOperation;
    publishmentOperation: PublishmentOperation;
    createCampaignOperation: createCampaignOperation;
    updateCampaignOperation: UpdateCampaignOperation;
    updateCampaignImagesOperation?: unknown;
    updateMatchMapImagesOperation: UpdateMatchMapImagesOperation;
    updateMatchImagesOperation: UpdateMatchImagesOperation;
    updateMatchHighlightedImageOperation: UpdateMatchHighlightedImageOperation;
    updateMatchMusicsOperation: UpdateMatchMusicsOperation;
    addCampaignPlayersOperation: AddCampaignPlayersOperation;
    removeCampaignPlayersOperation: RemoveCampaignPlayersOperation;
    getCampaignsByUserIdOperation: GetCampaignsByUserIdOperation;
    addPlayerCharacterOperation: AddPlayerCharacterOperation;
    removePlayerCharacterOperation: RemovePlayerCharacterOperation;
    getCampaignCharactersOperation: GetCampaignCharactersOperation;
    getCharactersByPlayerOperation: GetCharactersByPlayerOperation;
    postCampaignBuyOperation: PostCampaignBuyOperation;
    confirmMatchPlayerPresenceOperation: ConfirmMatchPlayerPresenceOperation;
    confirmCampaignPlayerOperation: ConfirmCampaignPlayerOperation;
    updateCampaignCoverOperation: UpdateCampaignCoverOperation;
    removeCampaignImageOperation: RemoveCampaignImageOperation;
    transferDungeonMasterOperation: TransferDungeonMasterOperation;
    updateCampaignJournalHighlightOperation: UpdateCampaignJournalHighlightOperation;
    updateCampaignJournalPostOperation: UpdateCampaignJournalPostOperation;
    deleteCampaignJournalPostOperation: DeleteCampaignJournalPostOperation;
    updateCampaignPlayerNoteOperation: UpdateCampaignPlayerNoteOperation;
    removeCampaignPlayerNoteOperation: RemoveCampaignPlayerNoteOperation;
}
