import GetCampaignByIdOperation from 'src/core/campaigns/operations/campaigns/GetCampaignByIdOperation';
import createCampaignOperation from 'src/core/campaigns/operations/campaigns/CreateCampaignOperation';
import GetAllCampaignsOperation from 'src/core/campaigns/operations/campaigns/GetAllCampaignsOperation';
import UpdateMatchMapImagesOperation from 'src/core/campaigns/operations/campaigns/UpdateMatchMapImagesOperation';
import UpdateMatchMusicsOperation from 'src/core/campaigns/operations/campaigns/UpdateMatchMusicsOperation';
import UpdateCampaignOperation from 'src/core/campaigns/operations/campaigns/UpdateCampaignOperation';
import updateMatchDateOperation from 'src/core/campaigns/operations/campaigns/updateMatchDateOperation';
import PublishmentOperation from 'src/core/campaigns/operations/campaigns/PublishmentOperation';
import AddCampaignPlayersOperation from 'src/core/campaigns/operations/campaigns/AddCampaignPlayersOperation';
import RemoveCampaignPlayersOperation from 'src/core/campaigns/operations/campaigns/RemoveCampaignPlayersOperation';
import PostInvitationEmailOperation from 'src/core/campaigns/operations/PostInvitationEmailOperation';
import PostCampaignLogOperation from 'src/core/campaigns/operations/PostCampaignLogOperation';
import PostCampaignBuyOperation from 'src/core/campaigns/operations/PostCampaignBuyOperation';
import AddPlayerCharacterOperation from 'src/core/campaigns/operations/AddPlayerCharacterOperation';
import RemovePlayerCharacterOperation from 'src/core/campaigns/operations/RemovePlayerCharacterOperation';
import GetCampaignCharactersOperation from 'src/core/campaigns/operations/GetCampaignCharactersOperation';
import GetCharactersByPlayerOperation from 'src/core/campaigns/operations/GetCharactersByPlayerOperation';
import GetCampaignsByUserIdOperation from 'src/core/users/operations/users/GetCampaignsByUserIdOperation';
import UpdateCampaignPlayerLimitOperation from 'src/core/campaigns/operations/UpdateCampaignPlayerLimitOperation';
import ConfirmMatchPlayerPresenceOperation from 'src/core/campaigns/operations/ConfirmMatchPlayerPresenceOperation';
import ConfirmCampaignPlayerOperation from 'src/core/campaigns/operations/ConfirmCampaignPlayerOperation';
import UpdateCampaignCoverOperation from 'src/core/campaigns/operations/UpdateCampaignCoverOperation';
import RemoveCampaignImageOperation from 'src/core/campaigns/operations/RemoveCampaignImageOperation';
import TransferDungeonMasterOperation from 'src/core/campaigns/operations/TransferDungeonMasterOperation';
import UpdateMatchCharacterPictureOperation from 'src/core/campaigns/operations/UpdateMatchCharacterPictureOperation';
import UpdateCampaignJournalHighlightOperation from 'src/core/campaigns/operations/UpdateCampaignJournalHighlightOperation';
import UpdateCampaignJournalPostOperation from 'src/core/campaigns/operations/UpdateCampaignJournalPostOperation';
import DeleteCampaignJournalPostOperation from 'src/core/campaigns/operations/DeleteCampaignJournalPostOperation';
import DeleteCampaignOperation from 'src/core/campaigns/operations/DeleteCampaignOperation';

export interface CampaignsControllerContract {
    deleteCampaignOperation: DeleteCampaignOperation;
    getAllCampaignsOperation: GetAllCampaignsOperation;
    getCampaignByIdOperation: GetCampaignByIdOperation;
    publishmentOperation: PublishmentOperation;
    createCampaignOperation: createCampaignOperation;
    updateCampaignOperation: UpdateCampaignOperation;
    updateMatchMapImagesOperation: UpdateMatchMapImagesOperation;
    updateMatchMusicsOperation: UpdateMatchMusicsOperation;
    updateMatchDateOperation: updateMatchDateOperation;
    addCampaignPlayersOperation: AddCampaignPlayersOperation;
    removeCampaignPlayersOperation: RemoveCampaignPlayersOperation;
    getCampaignsByUserIdOperation: GetCampaignsByUserIdOperation;
    addPlayerCharacterOperation: AddPlayerCharacterOperation;
    removePlayerCharacterOperation: RemovePlayerCharacterOperation;
    getCampaignCharactersOperation: GetCampaignCharactersOperation;
    getCharactersByPlayerOperation: GetCharactersByPlayerOperation;
    postInvitationEmailOperation: PostInvitationEmailOperation;
    postCampaignLogOperation: PostCampaignLogOperation;
    postCampaignBuyOperation: PostCampaignBuyOperation;
    updateCampaignPlayerLimitOperation: UpdateCampaignPlayerLimitOperation;
    confirmMatchPlayerPresenceOperation: ConfirmMatchPlayerPresenceOperation;
    confirmCampaignPlayerOperation: ConfirmCampaignPlayerOperation;
    updateCampaignCoverOperation: UpdateCampaignCoverOperation;
    removeCampaignImageOperation: RemoveCampaignImageOperation;
    transferDungeonMasterOperation: TransferDungeonMasterOperation;
    updateMatchCharacterPictureOperation: UpdateMatchCharacterPictureOperation;
    updateCampaignJournalHighlightOperation: UpdateCampaignJournalHighlightOperation;
    updateCampaignJournalPostOperation: UpdateCampaignJournalPostOperation;
    deleteCampaignJournalPostOperation: DeleteCampaignJournalPostOperation;
}
