import ActivateTwoFactorOperation from 'src/core/users/operations/users/ActivateTwoFactorOperation';
import AddCampaignNoteOperation from 'src/core/users/operations/users/AddCampaignNoteOperation';
import CreateUserOperation from 'src/core/users/operations/users/CreateUserOperation';
import DeactivateTwoFactorOperation from 'src/core/users/operations/users/DeactivateTwoFactorOperation';
import DeleteUserOperation from 'src/core/users/operations/users/DeleteUserOperation';
import GetUserByIdOperation from 'src/core/users/operations/users/GetUserByIdOperation';
import GetUsersOperation from 'src/core/users/operations/users/GetUsersOperation';
import PictureProfileOperation from 'src/core/users/operations/users/PictureProfileOperation';
import PostSupportEmailOperation from 'src/core/users/operations/users/PostSupportEmailOperation';
import RegisterDonationOperation from 'src/core/users/operations/users/RegisterDonationOperation';
import RemoveUserCoverOperation from 'src/core/users/operations/users/RemoveUserCoverOperation';
import UpdateEmailOperation from 'src/core/users/operations/users/UpdateEmailOperation';
import UpdatePasswordOperation from 'src/core/users/operations/users/UpdatePasswordOperation';
import UpdateUserOperation from 'src/core/users/operations/users/UpdateUserOperation';
import UpdateUserCoverOperation from 'src/core/users/operations/users/UpdateUserCoverOperation';
import UpdateUserDetailsOperation from 'src/core/users/operations/users/UpdateUserDetailsOperation';
import VerifyEmailOperation from 'src/core/users/operations/users/VerifyEmailOperation';
import LogoutUserOperation from 'src/core/users/operations/users/LogoutUserOperation';
import LoginUserOperation from 'src/core/users/operations/users/LoginUserOperation';
import { IUsersSchemas } from './UsersSchemas';
import SchemaValidator from 'src/domains/common/helpers/SchemaValidator';
import GetCampaignsByUserIdOperation from 'src/core/users/operations/users/GetCampaignsByUserIdOperation';
import MessagesOperation from 'src/core/users/operations/users/MessagesOperation';
import GalleryOperation from 'src/core/users/operations/users/GalleryOperation';
import FriendsOperation from 'src/core/users/operations/users/FriendsOperation';

export interface UsersControllerContract {
    schemaValidator: SchemaValidator;
    usersSchemas: IUsersSchemas;
    createUserOperation: CreateUserOperation;
    updateUserOperation: UpdateUserOperation;
    updateUserDetailsOperation: UpdateUserDetailsOperation;
    verifyEmailOperation: VerifyEmailOperation;
    getUsersOperation: GetUsersOperation;
    getUserByIdOperation: GetUserByIdOperation;
    activateTwoFactorOperation: ActivateTwoFactorOperation;
    deactivateTwoFactorOperation: DeactivateTwoFactorOperation;
    updateEmailOperation: UpdateEmailOperation;
    updatePasswordOperation: UpdatePasswordOperation;
    addCampaignNoteOperation: AddCampaignNoteOperation;
    pictureProfileOperation: PictureProfileOperation;
    postSupportEmailOperation: PostSupportEmailOperation;
    registerDonationOperation: RegisterDonationOperation;
    removeUserCoverOperation: RemoveUserCoverOperation;
    deleteUserOperation: DeleteUserOperation;
    logoutUserOperation: LogoutUserOperation;
    loginUserOperation: LoginUserOperation;
    getCampaignsByUserIdOperation: GetCampaignsByUserIdOperation;
    updateUserCoverOperation: UpdateUserCoverOperation;
    messagesOperation: MessagesOperation;
    galleryOperation: GalleryOperation;
    friendsOperation: FriendsOperation;
}
