#!/bin/bash
. "$(dirname -- "$0")/_/husky.sh"

BRANCH=$(git symbolic-ref --short HEAD)
REGEX="^(feat|bugfix|hotfix)\/([[:alnum:]-]+)\/([[:alnum:]-]+)$"

handlePrettierError() {
  npm run prettier:fix && git add . && git commit -m "fix: prettier" && git push -u origin $BRANCH
}

trap 'handlePrettierError $LINENO' ERR

npx tsc && npm run lint && npm run prettier

if [[ ! $BRANCH =~ $REGEX ]]; then
  echo "========================"
  echo ""
  echo -e "> \e[31mYour push was rejected due to the branch name\e[0m"
  echo ""
  echo -e "> Please rename your branch using the syntax: \e[32m(feat|bugfix|hotfix)\/\e[34mtask-id\/\e[33mbranch-objective\e[0m"
  echo "> Pushes in the develop, main, or qa branches are not allowed."
  echo ""
  echo "========================"
  exit 1
fi
